FROM node:20

WORKDIR /frontend-build

# Copy only package files first for better caching
COPY frontend/package*.json ./
RUN npm ci --force

# Now copy the rest of the code
COPY frontend .

# Copy over the .env and settings.yml files (due to RUN BUILD, they're needed BEFORE the volume would mount)
COPY .env /etc/abbey/.env
COPY settings.yml /etc/abbey/settings.yml

# Build the Next.js app
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
